veeHD.py dependency on plugin.video.dailyflix
fix for issue raised here https://github.com/Eldorados/script.module.urlresolver/issues/41

Recent changes to veeHD.py have included a dependency on plugin.video.dailyflix
If plugin.video.dailyflix is not installed ProjectFreeTv plugin fails with
RuntimeError: Could not get AddonPtr given a script id of plugin.video.dailyflix